language: node_js

node_js:
 - "0.10"

notifications:
  irc:
    channels:
      - "irc.mozilla.org#fxa"
    use_notice: false
    skip_join: false

before_install:
  - npm config set spin false

before_script:
  - npm i grunt-cli -g
  - npm run outdated

script:
  - npm test
