language: node_js

node_js:
 - "0.10"

notifications:
  email:
    - dcoates@mozilla.com
    - achilton@mozilla.com
    - jrgm@mozilla.com
    - rfkelly@mozilla.com
  irc:
    channels:
      - "irc.mozilla.org#fxa"
    use_notice: false
    skip_join: false

before_script:
  - npm i grunt-cli -g
  - npm run outdated
  - grunt validate-shrinkwrap

install:
  - npm install --no-optional

script:
  - npm test
